name: xdg_locale
description: Native Dart client library to access the D-Bus interface of systemd-localed.
version: 0.0.1

homepage: https://github.com/canonical/xdg_locale.dart

environment:
  sdk: ^3.0.0

platforms:
  linux:

dependencies:
  dbus: ^0.7.8
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.4
  lints: ^2.0.0
  mockito: ^5.4.1
  test: ^1.21.0
